FROM quay.io/centos/centos:stream8
LABEL maintainer="Kevin Carter <kecarter@redhat.com>"

RUN dnf -y update && \
    dnf -y --nobest install sudo \
                   yum-utils \
                   rpm-build \
                   dnf-plugins-core \
                   centos-release-openstack-xena \
                   python3-rpm \
                   python3-wheel && \
    useradd builder -u 1000 -m -G users,wheel || true && \
    echo "builder ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    echo "# macros"                        >  /home/builder/.rpmmacros && \
    echo "%_topdir    /home/builder/build" >> /home/builder/.rpmmacros && \
    echo "%_sourcedir %{_topdir}"          >> /home/builder/.rpmmacros && \
    echo "%_builddir  %{_topdir}"          >> /home/builder/.rpmmacros && \
    echo "%_specdir   %{_topdir}"          >> /home/builder/.rpmmacros && \
    echo "%_rpmdir    %{_topdir}"          >> /home/builder/.rpmmacros && \
    echo "%_srcrpmdir %{_topdir}"          >> /home/builder/.rpmmacros && \
    mkdir -p /home/builder/rpm && \
    chown -R builder /home/builder/rpm && \
    mkdir -p /home/builder/build && \
    chown -R builder /home/builder/build && \
    echo '%builder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY directord.tar.gz /home/builder/build/
RUN tar -O -xzf /home/builder/build/directord.tar.gz directord*/contrib/rpm/directord.spec > /home/builder/build/directord.spec
COPY builder.sh /home/builder/
USER builder
CMD /home/builder/builder.sh
