FROM quay.io/centos/centos:stream8
LABEL maintainer="Kevin Carter <kecarter@redhat.com>"

RUN dnf -y update && \
    dnf -y install sudo \
                   yum-utils \
                   rpm-build \
                   dnf-plugins-core \
                   centos-release-openstack-wallaby \
                   python3-rpm \
                   python3-wheel && \
    useradd builder -u 1000 -m -G users,wheel && \
    echo "builder ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    echo "# macros"                        >  /home/builder/.rpmmacros && \
    echo "%_topdir    /home/builder/build" >> /home/builder/.rpmmacros && \
    echo "%_sourcedir %{_topdir}"          >> /home/builder/.rpmmacros && \
    echo "%_builddir  %{_topdir}"          >> /home/builder/.rpmmacros && \
    echo "%_specdir   %{_topdir}"          >> /home/builder/.rpmmacros && \
    echo "%_rpmdir    %{_topdir}"          >> /home/builder/.rpmmacros && \
    echo "%_srcrpmdir %{_topdir}"          >> /home/builder/.rpmmacros && \
    mkdir -p /home/builder/rpm && \
    chown -R builder /home/builder/rpm && \
    mkdir -p /home/builder/build && \
    chown -R builder /home/builder/build && \
    echo '%builder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# TODO(cloudnull): remove all this when diskcache and ssh-python are packaged
RUN dnf -y install rpmdevtools python3-pytoml python3-pyxdg python38-requests cmake openssl openssl-devel python3-devel && \
    dnf -y groupinstall 'Development Tools' && \
    python3 -m venv /home/builder/pyp2rpm --system-site-packages && \
    /home/builder/pyp2rpm/bin/pip install pyp2rpm && \
    /home/builder/pyp2rpm/bin/pyp2rpm --srpm diskcache -d /home/builder/rpm -b 3 && \
    rpmbuild --rebuild "$(ls -1 /home/builder/rpm/python*-diskcache*.src.rpm)"  --nodeps --nocheck && \
    /home/builder/pyp2rpm/bin/pyp2rpm --srpm ssh-python -d /home/builder/rpm -b 3 && \
    rpmbuild --rebuild "$(ls -1 /home/builder/rpm/python*-ssh-python*.src.rpm)"  --nodeps --nocheck && \
    find ~/rpmbuild/RPMS -name '*.rpm' -exec cp "{}" /home/builder/build/ \; && \
    dnf -y install $(find /home/builder/build/ -name '*rpm' ! -name '*src*' -type f)

COPY directord.spec /home/builder/build/
COPY directord.tar.gz /home/builder/build/
COPY builder.sh /home/builder/
USER builder
CMD /home/builder/builder.sh
