#!/usr/bin/env bash
export DIRECTOR_SERVER_ADDRESS=${DIRECTOR_SERVER_ADDRESS:-localhost}
export DIRECTOR_MODE=${DIRECTOR_MODE:-client}

if [ "${DIRECTOR_MODE}" = "server" ]; then
    /directord/bin/directord --socket-path /tmp/directord.sock server
else
    /directord/bin/directord client --server-address ${DIRECTOR_SERVER_ADDRESS}
fi
