#!/usr/bin/env bash
export DIRECTOR_SERVER_ADDRESS=${DIRECTOR_SERVER_ADDRESS:-localhost}
export DIRECTOR_MODE=${DIRECTOR_MODE:-client}

if [ "${DIRECTOR_MODE}" = "server" ]; then
    /director/bin/director server --socket-path /tmp/director.sock
else
    /director/bin/director client --server-address ${DIRECTOR_SERVER_ADDRESS}
fi
